#ifndef _DEBUG_MENU_H_
#define _DEBUG_MENU_H_

typedef enum {
	ENTRY_VERSION,
	ENTRY_FPS,
	ENTRY_POS,
	ENTRY_YAW,
	ENTRY_PITCH,
	ENTRY_TIME,
	ENTRY_DAYLIGHT,
	ENTRY_SUN_ANGLE,
	ENTRY_HUMIDITY,
	ENTRY_TEMPERATURE,
	ENTRY_SEED,
	ENTRY_FLIGHT,
	ENTRY_COLLISION,
	ENTRY_TIMELAPSE,
	ENTRY_FULLSCREEN,
	ENTRY_OPENGL,
	ENTRY_GPU,
	ENTRY_ANTIALIASING,
	ENTRY_MIPMAP,
	ENTRY_VIEW_DISTANCE,
	ENTRY_LOAD_DISTANCE,
	COUNT_ENTRY,
} DebugMenuEntry;

void debug_menu_init();
void debug_menu_toggle();
void debug_menu_changed(DebugMenuEntry entry);
void debug_menu_update();

#endif // _DEBUG_MENU_H_
